engines:
  bundler-audit:
    enabled: true

  duplication:
    enabled: true
    languages:
      ruby:

  fixme:
    enabled: true

  rubocop:
    enabled: true

ratings:
  paths:
    - Gemfile.lock
    - "**.rb"
